# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f3808c9d418d75c880af69f5861563780049b9ed939e968ecfa1fc33ae1f3b264a25feab389b4b23c1e01791e00322159b7a42c52f65a1af2cb11fe3c702ef4

test:
  secret_key_base: 61e2e180fb7f544b19048eab8548d2365f430a54869357300943aec71f7905f9f49509d1ad86490bc06bc66ac920bd8a89815bd88eab84d4be29ddb379efdac8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
